### ISSUE TITLE
Staking Guide Incorrect Issue

### ISSUE THREAD

**Issue by letspesl** [truechain/truechain-engineering-code#120]
1. In the followings, there is sentence "After deposit, the node becomes a validator candidate. Only if the deposit balance > 50000(true), the validator can be selected as a candidate.".
https://github.com/truechain/truechain-engineering-code/wiki/Staking-Contract#interact-with-contract-interface
But, in the followings, there is sentence "Validators are the DPoS committee members to process transactions. The minimum amount to be validator is 20,000 TRUE."
https://github.com/truechain/truechain-engineering-code/wiki/Staking-Guide#validator
It seems to me that 20,000 TRUE is the minimum requirement. Is it correct? If it correct, I think that it need to be changed first document. What is correct information?

2. In the followings, It seems that the asset is not available until 25000 fast blocks have passed after executing withdraw.
https://github.com/truechain/truechain-engineering-code/wiki/Staking-Guide#locked-time
But currently, it seems that it takes about 6 seconds to create 1 fast block.
If so, doesn't it take about 42 hours rather than 15 days to create a 25000 fast block?
If not, how long does it take to create 1 fast block currently? Is it correct that it takes 15 days to become unfreeze?

**Comment by jiyilanzhou** [comment]
1. Thank feedback，aleady update to  20,000 TRUE。
2. you can read this code.https://github.com/truechain/truechain-engineering-code/blob/aea829b22868b394ae616ff82d6319d1886e69ae/core/types/impawnUtil.go#L418
```
	MaxRedeemHeight            uint64 = 250000 // about 15 days
	NewEpochLength             uint64 = 25000  // about 1.5 days
```
* first ，you withdraw height need account  from unlock height to current epoch over height，This largest 25000.
* second , MaxRedeemHeight +1.

**Comment by letspesl** [comment]
I understood your answer to (2) this way.
The asset is not available until 10 epoch have passed after executing withdraw and 1 epoch is 25000 fast blocks.
Is it right?
If it so, how can I get current epoch? Is there some API to get epoch number?

**Comment by jiyilanzhou** [comment]
please use api `etrue.committeeNumber` get epoch.

**Comment by letspesl** [comment]
Thanks for fast answers!
