### ISSUE TITLE
which branch could build sucessfully

### ISSUE THREAD

**Issue by dipingxian2** [truechain/truechain-engineering-code#19]
I update code to  latest version of "truechain/truechain-engineering-code", and then  run "make getrue" or "make all", get folllowing errors:
consensus/minerva/algorithm.go:30:2: cannot find package "github.com/ethereum/go-ethereum/common" in any of:
	/nfs/gopath/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/vendor/github.com/ethereum/go-ethereum/common (vendor tree)
	/usr/local/go/src/github.com/ethereum/go-ethereum/common (from $GOROOT)
	/nfs/gopath/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/ethereum/go-ethereum/common (from $GOPATH)
consensus/minerva/algorithm.go:31:2: cannot find package "github.com/ethereum/go-ethereum/common/bitutil" in any of:
	/nfs/gopath/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/vendor/github.com/ethereum/go-ethereum/common/bitutil (vendor tree)
	/usr/local/go/src/github.com/ethereum/go-ethereum/common/bitutil (from $GOROOT)
	/nfs/gopath/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/ethereum/go-ethereum/common/bitutil (from $GOPATH)
consensus/minerva/algorithm.go:33:2: cannot find package "github.com/ethereum/go-ethereum/crypto/sha3" in any of:
	/nfs/gopath/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/vendor/github.com/ethereum/go-ethereum/crypto/sha3 (vendor tree)
	/usr/local/go/src/github.com/ethereum/go-ethereum/crypto/sha3 (from $GOROOT)
	/nfs/gopath/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/ethereum/go-ethereum/crypto/sha3 (from $GOPATH)
consensus/minerva/algorithm.go:34:2: cannot find package "github.com/ethereum/go-ethereum/log" in any of:
	/nfs/gopath/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/vendor/github.com/ethereum/go-ethereum/log (vendor tree)
	/usr/local/go/src/github.com/ethereum/go-ethereum/log (from $GOROOT)
	/nfs/gopath/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/ethereum/go-ethereum/log (from $GOPATH)
p2p/simulations/adapters/inproc.go:31:2: cannot find package "github.com/truechain/truechain-engineering-code/p2p/simulations/pipes" in any of:
	/nfs/gopath/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/vendor/github.com/truechain/truechain-engineering-code/p2p/simulations/pipes (vendor tree)
	/usr/local/go/src/github.com/truechain/truechain-engineering-code/p2p/simulations/pipes (from $GOROOT)
	/nfs/gopath/src/github.com/truechain/truechain-engineering-code/build/_workspace/src/github.com/truechain/truechain-engineering-code/p2p/simulations/pipes (from $GOPATH)
util.go:45: exit status 1

it seems that there are some packages in the source code can't be found  or there are some code refers  wrong path of packages?

**Comment by hyangl** [comment]
Thanks for test,  I have fixed this bug.
