### ISSUE TITLE
The necessary functions of API do not work

### ISSUE THREAD

**Issue by existencer** [truechain/truechain-engineering-code#30]
APIs `func (self *worker) pendingBlock() *types.Block` and `func (self *worker) pending() (*types.Block, *state.StateDB)` can not return the correct result (`miner/worker.go:L234-270`), which are necessary interfaces for many Web3 functions.

Danger level: 1/5
Importance level: 4/5

**Comment by ruthlesstom** [comment]
![null_photos_color_200x200dp_2x](https://user-images.githubusercontent.com/37338437/48477476-b5d9da80-e7cf-11e8-9b82-36e088af1442.png)
