### ISSUE TITLE
BAD SNAIL BLOCK 

### ISSUE THREAD

**Issue by sdwp111** [truechain/truechain-engineering-code#35]
ERROR[12-12|14:16:27.822] 
########## BAD SNAIL BLOCK #########
Chain config: {ChainID: 1 Engine: {MinimumDifficulty: 10000 MinimumFruitDifficulty: 100 DurationLimit: 60}}

Number: 8842
Hash: 0x5812a026d4a76853dc718dafc419ea197c294c5f015fdd162f6639dac5de3da5

Error: invalid parents
##############################

**Comment by hyangl** [comment]
It is a normal message when received an uncle snail block.
