### ISSUE TITLE
Local maintenance of the maximum height of the fast chain of the connector

### ISSUE THREAD

**Issue by shijinyuan** [truechain/truechain-engineering-code#41]
For the synchronization of fast chain, the maximum height block of the other party will be requested once for each comparison of whether there is a gap between the height of the other party node and that of the other party node. Therefore, a maintenance of the maximum height block of the other party node will be added locally

**Comment by jiyilanzhou** [comment]
https://github.com/truechain/truechain-engineering-code/commit/d1fe3af1aadfe93317df5e6a671d5f3dfc53aedd

**Comment by shijinyuan** [comment]
Has been completed
