### ISSUE TITLE
SingleNode Mode  works only with --bftkeyhex c1581e25937d9ab91421a3e1a2667c85b0397c75a195e643109938e987acecfc

### ISSUE THREAD

**Issue by bluesea0125** [truechain/truechain-engineering-code#54]
SingleNode Mode  works only with --bftkeyhex c1581e25937d9ab91421a3e1a2667c85b0397c75a195e643109938e987acecfc. I tried bftkey in ~/.truechain/getrue, invalid committee members error showed up.

**Comment by shuxunyer** [comment]
Is the genesis file that you are  initializing with genesis_single.json
like this : --datadir ./data  init genesis_single.json

**Comment by bluesea0125** [comment]
yes. I don't understand why it uses only static value. If so, what is bftkey in .truechain/getrue for?
And this is another question. I tried truechain with genesis.json, but failed. I could not find any guide for it. It will be helpful if any guide for multi-node mode is published.

**Comment by bluesea0125** [comment]
I found the solution. public key(0x04044308742b61976de7344edb8662d6d10be1c477dd46e8e4c433c1288442a79183480894107299ff7b0706490f1fb9c9b7c9e62ae62d57bd84a1e469460d8ac1) in genesis_single.json and bftkey(c1581e25937d9ab91421a3e1a2667c85b0397c75a195e643109938e987acecfc) are matched. That's, the public key is generated from the bftkey. public keys are used to identify the committee members and they are inserted into snailblock when genesised. That's why genesis.json is useless. You should find your own keypairs(bftkey, publickey) before you start testing.
