### ISSUE TITLE
Snail block not on the chain 

### ISSUE THREAD

**Issue by ycjmail** [truechain/truechain-engineering-code#72]
testing 0.9.7 version, get "Snail block not on the chain" error below
INFO [01-31|12:57:06.325] Received complete proposal block         height=12665 hash=973662…ac125e
INFO [01-31|12:57:06.326] enterPrevote(12665/32). Current: 12665/32/RoundStepPropose 
INFO [01-31|12:57:06.327] Finalize:                                header.SnailHash=17e0a3…5a721b header.SnailNumber=199
INFO [01-31|12:57:06.328] Finalize: verifyFastBlock                Height:=12665
ERROR[01-31|12:57:06.329] verifyFastBlock process error            height:=12665 err="Snail block not on the chain"
WARN [01-31|12:57:06.330] vote AgreeAgainst                        number=12665 hash=973662…ac125e

**Comment by hyangl** [comment]
#36

**Comment by hyangl** [comment]
The same issue #36

**Comment by ycjmail** [comment]
thanks for your reply.
if I use 1 miner node ,the error donot appear ;
if I use 2 miner node ,the error  appear in less than 2000 fastblocknode .
