### ISSUE TITLE
add fast block time interval check when insert snail block

### ISSUE THREAD

**Issue by hyangl** [truechain/truechain-engineering-code#76]
Now only checks the fruits count when inserting a snail block. 
But there is a problem, that when fast blocks are proposed so quickly about one block per second, the miners still mine snail block  every 60 fruits. 
There will be a lot of fruits to be mined but most hash power is mining snail block. 
Then committee will stop propose fas block when more than 1200 fast blocks not be mined. 
So we should have a mechanism that the snail block should include more fruits when fast block is proposed quickly.Here we can validate the time interval between the fast blocks included in the snail block.

**Comment by ljs19850321** [comment]
can you run in main?
