### ISSUE TITLE
invalid fruits time gap

### ISSUE THREAD

**Issue by rice-mouse** [truechain/truechain-engineering-code#95]
INFO [06-02|22:19:03.669] ValidateBody snail validate time gap error block=9780 first fb number=1135902 first fb time=1559395623 last fb number=1135976 last fb time=1559395982 tim gap=359
ERROR[06-02|22:19:03.670] 
########## BAD SNAIL BLOCK #########
Chain config: {ChainID: 19330 Engine: {MinimumDifficulty: 134217728 MinimumFruitDifficulty: 262144 DurationLimit: 600}}

Number: 9780
Hash: 0x982c75413ada68c702a26d37b34c67fc0a447105cfc57b217be189dfcfeb2dd8

Error: invalid fruits time gap
##############################
 
ERROR[06-02|22:19:03.670] Snail downloaded item processing failed  number=0xaded30 hash=982c75…eb2dd8 err="invalid fruits time gap"

**Comment by hyangl** [comment]
Can you tell me about your getrue version?

After the version 1.0, snail block's body invalidation method validates the time interval between the fast blocks whose fruits are included at this snail block.

If the snail block is not mined by you, you can ignore this message, and try the [lasted release version]( https://github.com/truechain/truechain-engineering-code/releases).
